### ISSUE TITLE
conda install returns error

### ISSUE THREAD

**Issue by BayesForDays** [coryshain/dtsr#10]
Hi, I am attempting to install the package and its dependencies to replicate the analyses of your 2023 paper. I am providing this error in case anyone has issues -- I am running `conda=23.9.0` with python `3.12.0` on an M2 Macbook Pro so there may be architectural differences. I have been using the command `conda env create -f conda_cdr.yml` but it yields tensorflow errors:

```
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement tensorflow>=1.9 (from versions: none)
ERROR: No matching distribution found for tensorflow>=1.9
```

I believe the issue is about compatibility with my specific version of Python. Therefore, I did the following, which solved the installation issues with `pip`:

```
cd /path/to/repo
conda create -n cdr python=3.8
conda env update -n cdr --file conda_cdr.yml
```

For what it's worth, I am happy to make a yml config that works from conda specifically. If you'd like, I can make a pull request to change your installation instructions to specify a Python version. I didn't test 3.9/3.10/3.11, just 3.8.

I have not tested whether the code still works with later versions of tensorflow. If the version needs to be `1.9` I will return and create a new issue.

**Comment by coryshain** [comment]
Thanks for pointing this out! This is a new dependency conflict: apparently tensorflow doesn't currently support Python 3.12 (https://github.com/tensorflow/tensorflow/issues/62003). I've pushed patches to the conda configs in the master, dev, and pred_fn branches (pred_fn is the reproduction branch for the paper I think you're targeting), though hopefully this will only be a temporary situation.
