### ISSUE TITLE
Response variable "1" is ignored in model formula

### ISSUE THREAD

**Issue by hans** [coryshain/dtsr#9]
A multivariate model specified to include a response variable `1`  does not actually include this response variable. You can reproduce this with [this attached zipfile](https://github.com/coryshain/cdr/files/8490240/f445dbb_1.zip) and CDR at commit f445dbb :

```
$ grep \^formula synth.ini
formula = y + 1 ~ C(a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + q + r + s + t, NN()) 
$ python -m cdr.bin.train synth.ini
...
---------------------- INITIALIZATION SUMMARY ---------------------- 
   MODEL FORMULA:     y ~ C(a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + q + r + s + t, NN()) 
```

If we have a univariate response `1`, this triggers a crash:

```
$ grep \^formula synth_uni.ini
formula = 1 ~ C(a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + q + r + s + t, NN()) 
$ python -m cdr.bin.train synth.ini
...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/cdr/cdr/bin/train.py", line 34, in <module>
    p = Config(args.config_path)
  File "/opt/cdr/cdr/config.py", line 123, in __init__
    formula = Formula(config[model_field]['formula'])
  File "/opt/cdr/cdr/formula.py", line 251, in __init__
    self.build(bform_str, standardize=standardize)
  File "/opt/cdr/cdr/formula.py", line 271, in build
    self.process_ast(dv.body[0].value, terms=dv_term, under_irf=True) # Hack: use under_irf=True to prevent function from transforming DV into Dirac Delta IRF
IndexError: list index out of range
```

### Desired behavior

Either don't quietly drop this response variable, or document/show a warning.

**Comment by coryshain** [comment]
Thanks for pointing this out! Variable names need to be valid Python identifiers, so numbers aren't supported as variable names in formulas (R formulas have similar rules). Diagnosing whether the user intended the number to be a variable name (in order to throw a warning) is a bit tricky, but I'll think about ways of doing this. Meanwhile, I'll add a note to the docs. In your case, just translate the response variable names into valid Python variable names.

**Comment by hans** [comment]
Thanks, good to have more informative variable names in any case, but just wanted to note the bug/surprise :)

> so numbers aren't supported as variable names in formulas
It's actually a little stranger than that -- other numbers (e.g. `12`) are retained in the model formula. Only `1` is dropped (out of the positive nonzero integers I've tried!).

**Comment by coryshain** [comment]
It's because the same parser is applied to the left and right hand sides, and 1 is a reserved name for the intercept on the RHS. Numbers as variable names just isn't a use case I anticipated, so behavior will be unexpected.
